int print_char(char c);
char *string_copy(char *dest, const char *src);
char *string_ncopy(char *dest, const char *src, int n);
char *rev_string(char *str);
char *string_string(const char *haystack, const char *needle);
int strings_compare(char *s1, const char *s2);
int strings_n_compare(char *s1, const char *s, size_t n);
char *uppercase_string(char *);
char *lowercase_string(char *);
char *cap_string(char *);
int string_alpha(char *s);
int string_digit(char *s);
int string_lower(char *s);
int string_upper(char *s);
int string_printable(char *s);
int is_prime_number(int n, int i);
